version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: canalsugar2
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canalSugar2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/canalsugar2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      SERVER_PORT: 8081
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data: